spring.application.name=turfBookingSystemBackend

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/turf_booking_system
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

